[package]
name = "polygon_renderer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.35.2"
gltf = "1.0.0"

[[bin]]
name = "polygon_renderer"
path = "src/main.rs"
