[package]
name = "polygon_renderer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.35.2"
image = "0.24.3"
regex = "1"

[[bin]]
name = "polygon_renderer"
path = "src/main.rs"
